### ISSUE TITLE
Corrected group names are not propagated

### ISSUE THREAD

**Issue by adrientetar** [googlei18n/ufo2ft#13]
KernFeatureWriter crashes [here](https://github.com/jamesgk/ufo2ft/blob/cd64b39/Lib/ufo2ft/kernFeatureWriter.py#L192) because while leftClasses has corrected group names, self.classPairKerning still has the original names.

```
Traceback (most recent call last):
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\fontView.py", line 988, in exportFile
    otf = self.font.getRepresentation("defconQt.TTFont")
  File "C:\Python34\lib\site-packages\defcon\objects\base.py", line 337, in getRepresentation
    representation = factory["factory"](self, **kwargs)
  File "C:\Users\Admin\Downloads\trufont\Lib\defconQt\representationFactories\openTypeFactory.py", line 5, in TTFontFactory
    otf = compileOTF(font)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 29, in compileOTF
    featureCompilerClass, kernWriter, markWriter)
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\__init__.py", line 18, in _compile
    featureCompiler.compile()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 26, in compile
    self.setupFile_features()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 59, in setupFile_features
    autoFeatures["kern"] = self.writeFeatures_kern()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\makeotfParts.py", line 83, in writeFeatures_kern
    return writer.write()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\kernFeatureWriter.py", line 57, in write
    self._removeConflictingKerningRules()
  File "C:\Python34\lib\site-packages\ufo2ft-0.1-py3.4.egg\ufo2ft\kernFeatureWriter.py", line 193, in _removeConflictingKerningRules
    lGlyphs = leftClasses[lClass]
KeyError: 'public.kern1.@MMK_L_FF000000000000023'
```

Content of leftClasses:

```
dict_keys(['@public.kern1.MMK_L_FF000000000000022', '@public.kern1.MMK_L_FF000000000000002', '@public.kern1.MMK_L_FF000000000000020', '@public.kern1.MMK_L_FF000000000000009', '@public.kern1.MMK_L_FF000000000000013', '@public.kern1.MMK_L_FF000000000000014', '@public.kern1.MMK_L_FF000000000000011', '@public.kern1.MMK_L_FF000000000000010', '@public.kern1.MMK_L_FF000000000000017', '@public.kern1.MMK_L_FF000000000000023', '@public.kern1.MMK_L_FF000000000000019', '@public.kern1.MMK_L_FF000000000000018', '@public.kern1.MMK_L_FF000000000000005', '@public.kern1.MMK_L_FF000000000000021', '@public.kern1.MMK_L_FF000000000000016', '@public.kern1.MMK_L_FF000000000000006', '@public.kern1.MMK_L_FF000000000000004', '@public.kern1.MMK_L_FF000000000000003', '@public.kern1.MMK_L_FF000000000000015', '@public.kern1.MMK_L_FF000000000000012', '@public.kern1.MMK_L_FF000000000000008', '@public.kern1.MMK_L_FF000000000000007'])
```

**Comment by adrientetar** [comment]
@jamesgk In `_collectUfoClasses` you are normalizing class names to be FEA-compatible, but in `_collectUfoKerning` you collect the unmodified group names of the UFO and then in `_removeConflictingKerningRules` you are looking for the unmodified names (`self.leftClassKerning`) in the dict of modified names (`leftClasses`, which contains `self.leftUfoClasses`).
