### ISSUE TITLE
Cast unitsPerEm to int?

### ISSUE THREAD

**Issue by mashabow** [googlei18n/ufo2ft#149]
I'm getting an error while compiling a ufo made with [`DesignSpaceProcessor`](https://github.com/LettError/designSpaceDocument/blob/51ddbfaf195b0a59e09b1631ba92ae8774ccb9a8/Lib/designSpaceDocument/ufoProcessor.py#L118):

```python
Python 3.6.1 (default, Jul 19 2017, 13:24:40)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from designSpaceDocument.ufoProcessor import DesignSpaceProcessor
>>> processor = DesignSpaceProcessor(ufoVersion=3)
>>> processor.read('test.designspace')
>>> processor.loadFonts()
>>> ufo = processor.makeInstance(processor.instances[0])
>>> from ufo2ft import compileOTF
>>> otf = compileOTF(ufo)
Underline thickness not set in UFO, defaulting to UPM * 0.05
Underline position not set in UFO, defaulting to UPM * -0.075
Underline thickness not set in UFO, defaulting to UPM * 0.05
Underline position not set in UFO, defaulting to UPM * -0.075
Underline thickness not set in UFO, defaulting to UPM * 0.05
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mnakamura/.pyenv/versions/3.6.1/lib/python3.6/site-packages/ufo2ft/__init__.py", line 44, in compileOTF
    postProcessor = PostProcessor(otf, ufo)
  File "/Users/mnakamura/.pyenv/versions/3.6.1/lib/python3.6/site-packages/ufo2ft/postProcessor.py", line 15, in __init__
    otf.save(stream)
  File "/Users/mnakamura/.pyenv/versions/3.6.1/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 219, in save
    self._writeTable(tag, writer, done)
  File "/Users/mnakamura/.pyenv/versions/3.6.1/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 658, in _writeTable
    tabledata = self.getTableData(tag)
  File "/Users/mnakamura/.pyenv/versions/3.6.1/lib/python3.6/site-packages/fontTools/ttLib/__init__.py", line 669, in getTableData
    return self.tables[tag].compile(self)
  File "/Users/mnakamura/.pyenv/versions/3.6.1/lib/python3.6/site-packages/fontTools/ttLib/tables/_h_e_a_d.py", line 64, in compile
    data = sstruct.pack(headFormat, self)
  File "/Users/mnakamura/.pyenv/versions/3.6.1/lib/python3.6/site-packages/fontTools/misc/sstruct.py", line 75, in pack
    data = struct.pack(*(formatstring,) + tuple(elements))
struct.error: required argument is not an integer
```

This error seems to be caused by `ufo.info.unitsPerEm`; fonttools expects an int but it is a float actually.

```python
>>> type(ufo.info.unitsPerEm)
<class 'float'>
>>> ufo.info.unitsPerEm
1000.0
```

**Comment by anthrotype** [comment]
Yes, we should use `round`.
